#!/usr/bin/env python

import subprocess as sp

string = sp.check_output('sensors', shell=True).decode().split('\n')

temps = []

_sum = 0
_len = 0

for line in string:
    if line[:4] == 'Core':
        try:
            temp = float(line.split('+')[1][:4])
            temps.append(temp)
            _sum += temp
            _len += 1
        except:
            pass

print(round(_sum/_len, 1))





