#!/bin/bash

echo "Mounting external HDD..."
cat /home/albert/.luksPS | sudo cryptsetup open --type=luks /dev/sda luks_container -
sudo mount /dev/mapper/luks_container /data

echo "Mounting RPi3(sshfs)..."

