#!/bin/sh
xrandr --output DP-5 --off --output DP-4 --mode 3840x2160 --pos 6000x360 --rotate normal --output DP-3 --off --output DP-2 --mode 3840x2160 --pos 0x0 --rotate left --output DP-1 --off --output DP-0 --primary --mode 3840x2160 --pos 2160x360 --rotate normal
