#!/bin/bash

# Sync files between folders

docs=~/Documents
docsT=/data/Files/Documents/

while true; do
	inotifywait -e modify -e create -e delete -e move -r $docs 2>/dev/null  && rsync -rc $docs/* $docsT --delete
done

