#!/bin/bash


echo "Copying configuration files..."
echo "-- terminator"
cp -r ~/.config/terminator/*	configurations/terminator
echo "-- tmux"
cp ~/.tmux.conf			configurations/tmux.conf
echo "-- zsh"
cp ~/.zshrc			configurations/.zshrc
echo "-- ranger"
cp ~/.config/ranger/rc.conf 	configurations/ranger

echo "-- packaged"
apt list --installed >> packages.txt


echo "DONE"

