#!/bin/bash

echo "Mounting external HDD..."
echo "==========================="
echo "Unencrypting..."
cat /home/athalbraht/.luksPS | cryptsetup open --type=luks /dev/sdb1 Tokyo -
cat /tmp/luks_callback
echo "Mounting..."
mount /dev/mapper/Tokyo /data
echo "==========================="



