#!/bin/bash

echo "Mounting external HDD..."
echo "==========================="
echo "Unencrypting..."
cat /home/albert/.luksPS | cryptsetup open --type=luks /dev/sdb3 hdd1TB -
cat /tmp/luks_callback
echo "Mounting..."
mount /dev/mapper/hdd1TB /data
echo "==========================="



